version: "2"
services:
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    # network_mode: bridge
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - INTERFACE=eth0 #optional
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    labels:
      kompose.service.type: LoadBalancer
